name: "Environment setup"
description: "Install tools like Java, Maven, Docker, Just, etc."

inputs:
  ossrh-username: { required: true, description: "Sonatype username" }
  ossrh-token: { required: true, description: "Sonatype token" }
  gpg-private-key: { required: false, description: "GPG private key" }
  gpg-passphrase: { required: false, description: "GPG passphrase" }

runs:
  using: "composite"
  steps:

    - name: Java Setup
      uses: actions/setup-java@v4.7.1
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
        server-id: central
        server-username: ${{ inputs.ossrh-username }}
        server-password: ${{ inputs.ossrh-token }}
        gpg-private-key: ${{ inputs.gpg-private-key }}
        gpg-passphrase: ${{ inputs.gpg-passphrase }}

    - name: Just Setup
      uses: taiki-e/install-action@just