name: Deploy snapshot to Maven Central

on:
  push:
    branches:
      - development

jobs:

  snapshot:
    name: Deploy snapshot to Maven Central
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:

      - name: Retrieve the sources
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup
        with:
          central-username: ${{ secrets.CENTRAL_USERNAME }}
          central-token: ${{ secrets.CENTRAL_TOKEN }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Deploy snapshot
        run: |
          just run_tests
          just run_deploy_snapshot