name: Deploy SNAPSHOT to Maven Central

on:
  push:
    branches:
      - development

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          central-username: ${{ secrets.CENTRAL_USERNAME }}
          central-token: ${{ secrets.CENTRAL_TOKEN }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Deploy SNAPSHOT
        run: |
          just run_tests
          just run_deploy