name: Push on development - Build, test, create spring boot starter

on:
  push:

jobs:

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:

      - name: Retrieve the sources
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup
        with:
          ossrh-username: ${{ secrets.OSSRH_USERNAME }}
          ossrh-token: ${{ secrets.OSSRH_TOKEN }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: build and run tests
        run: |
          just run_tests

  snapshot:
    name: Deploy SNAPSHOT
    needs: unit_tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    if: github.ref_type == 'branch' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development')
    steps:

      - name: Retrieve the sources
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup
        with:
          ossrh-username: ${{ secrets.OSSRH_USERNAME }}
          ossrh-token: ${{ secrets.OSSRH_TOKEN }}

      - name: Deploy SNAPSHOT
        run: |
          mvn -B -DskipTests deploy