name: Push on tag - Publish to Maven Central

on:
  push:
    tags: [ '*' ]

jobs:

  release:
    name: Release to Maven Central
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:

      - name: Retrieve the sources
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup
        with:
          ossrh-username: ${{ secrets.OSSRH_USERNAME }}
          ossrh-token: ${{ secrets.OSSRH_TOKEN }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Deploy
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mvn -B -Prelease -DskipTests deploy -Dgpg.passphrase=${GPG_PASSPHRASE}
